### ISSUE TITLE
CPMNetv2 Results on Aneurysms and RibFractures 

### ISSUE THREAD

**Issue by mibaumgartner** [zunzhumu/CPMNetv2#12]
Hi,

congratulations on your great work on CPMNetv2, this looks very interesting. The readme states that CPMNetv2 achieves very nice results on Aneurysm Detection on TOF-MRA (ADAM?) and RibFracture (RibFrac?) detection problems. Would it be possible to share those results and provide a citable source for them? (optimally also including the exact splits and experimental setup used to run those :) )

Best,
Michael

**Comment by zunzhumu** [comment]
Hello,  @Michael
        Thank you for your attention. The results of Aneurysm Detection and Rib Fracture are solely validated on our private dataset. Sorry, this repo is intended only to share a medical detection framework and is not prepared for publishing a paper.

Best,
Tao

**Comment by mibaumgartner** [comment]
Dear Tao,

thanks for the infos! :) 

Best,
Michael
