### ISSUE TITLE
How to reproduce the experiment on LUNA16?

### ISSUE THREAD

**Issue by XinKai-Tang** [zunzhumu/CPMNetv2#3]
It's a good job that CPM-Net can get excellent perfermance on LUNA16. Recently, I wanted to use CPM-NetV2 to reproduce this experiment, but I got failed. The performance of my CPM-NetV2 model is not satisfying (**its CPM is only 85.0**). Could you please provide me with some suggestions on **hyperparameters**?

**Comment by zunzhumu** [comment]
Thank you for using CPM-NetV2. Unfortunately, due to time constraints, the LUNA16 preprocessing script is not supported in my reconstructed code. However, I will provide a LUNA16 preprocessing script later this week. Please note that the directions of the nii.gz files may not be the same, which may affect your model's performance.

**Comment by Pang-b0** [comment]
> It's a good job that CPM-Net can get excellent perfermance on LUNA16. Recently, I wanted to use CPM-NetV2 to reproduce this experiment, but I got failed. The performance of my CPM-NetV2 model is not satisfying (**its CPM is only 85.0**). Could you please provide me with some suggestions on **hyperparameters**?

Hello, I have encountered some problems in data preprocessing. How do you set the path when preprocessing? Can you teach me some experience? Thank you.

**Comment by Pang-b0** [comment]
> 感谢您使用 CPM-NetV2。遗憾的是，由于时间限制，我的重建代码不支持 LUNA16 预处理脚本。但是，我将在本周晚些时候提供一个 LUNA16 预处理脚本。请注意，nii.gz 文件的方向可能不同，这可能会影响模型的性能。

Hello, can you provide a document about data preprocessing? I'm not sure how to divide data into training set and verification set (In the article, the first 9 folds mentioned are training set  the last folds  as validate set). How can I preprocess them? and put the processed data into training?

**Comment by MOMOANNIE** [comment]
> It's a good job that CPM-Net can get excellent perfermance on LUNA16. Recently, I wanted to use CPM-NetV2 to reproduce this experiment, but I got failed. The performance of my CPM-NetV2 model is not satisfying (**its CPM is only 85.0**). Could you please provide me with some suggestions on **hyperparameters**?

你好，请问你有用这个代码训练自己的数据吗？ 有没有遇到所有loss为0的情况哈？

**Comment by zunzhumu** [comment]
@Pang-b0 Luna16 dataset preprocessing script has been uploaded which need some adaptation work. Sorry to reply late.

**Comment by atisman89** [comment]
Hello. Same here. I'm trying to train CPMNetv2 with LUNA16 dataset. I've run the newly uploaded LUNA16 preprocessing script (`luna16_preprocessing.py`) and processed all data (which generated bunch of `.npz` files under the `process` folder). However, I was not able to figure out how these generated `.npz` files could be used in the existing training script and data loader. Could you provide some more information about it?

**Comment by HengfanLi** [comment]
> It's a good job that CPM-Net can get excellent perfermance on LUNA16. Recently, I wanted to use CPM-NetV2 to reproduce this experiment, but I got failed. The performance of my CPM-NetV2 model is not satisfying (**its CPM is only 85.0**). Could you please provide me with some suggestions on **hyperparameters**?

你好，请问可以交流一下。怎么复现代码吗？我的QQ是1401210020.

**Comment by Xx971007** [comment]
> CPM-Net 可以在 LUNA16 上获得出色的性能，这是一件好事。最近，我想使用 CPM-NetV2 重现这个实验，但我失败了。我的 CPM-NetV2 模型的性能不令人满意（**其 CPM 仅为 85.0**）。您能给我一些关于**超参数**的建议吗？

你好，看到您好像已经跑通了这个luna16的代码，非常开心知道luna16能够使用这个网络；我也在复现这个代码，但是在预处理的地方好像出现了问题，我无法得到网络需要的数据进行训练；您能够给我一些帮助和指导吗，我的V：xx15501522610，希望您能够联系我，然后我们可以进行进一步的沟通交流！
