### ISSUE TITLE
The loss is 0 during training

### ISSUE THREAD

**Issue by MOMOANNIE** [zunzhumu/CPMNetv2#7]
Hello, when I was training my own data, I found that the loss was still 0 when I reached the fifth epoch of training. Is there a problem with this? How to solve it?
![image](https://github.com/zunzhumu/CPMNetv2/assets/26375536/b4cb50f0-ca28-4662-aeb0-18be6af73ad5)

**Comment by huangguoqing** [comment]
@MOMOANNIE 这个是什么问题导致的？
